version: 2

project_name: podump

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: kubectl-podump
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

krews:
  - name: podump
    repository:
      owner: fnzv
      name: krew-index
    homepage: https://github.com/fnzv/kubectl-podump
    short_description: Dump pod network traffic
    description: |
      A command-line tool to quickly inspect network traffic.
    caveats: |
      Usage:
        kubectl podump [pod-name]
      Examples:
        kubectl podump -n monitoring prometheus port 9090
        kubectl podump my-app --pcap > capture.pcap
snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: fnzv
    name: podump